Fm 10
FedAGcom/FedAGMusic pull request #15
Opened 2022-09-21 20:50 UTC by Maksim97Q

2022-09-22 12:41 UTC, Aleksandr-Gurin commented on src/main/java/com/fedag/fedagmusic/controller/PlaylistController.java
> +        return playlistRepo.findPlaylistById(id)
Перенеси все меотды из playlistRepo в сервис и используй его здесь

2022-09-22 12:42 UTC, Aleksandr-Gurin commented on src/main/java/com/fedag/fedagmusic/controller/SongController.java
> +        return songRepo.findSongById(id)
перенеси в сервис

2022-09-22 12:45 UTC, Aleksandr-Gurin commented on src/main/java/com/fedag/fedagmusic/job/SubscriberCountPerformer.java
> +    @Scheduled(cron = "0 0 01 * * *")
запиши крон строку в конфиг и подтягивай её сюда из конфига

2022-09-22 12:48 UTC, Aleksandr-Gurin commented on src/main/java/com/fedag/fedagmusic/job/SubscriberCountPerformer.java
> +    public void SubscriberCount() {
метод с маленькой буквы

2022-09-22 12:49 UTC, Aleksandr-Gurin commented on src/main/java/com/fedag/fedagmusic/job/SubscriberCountPerformer.java
> +        System.out.println("total number of subscribers of performers = " + count);
log.debug из Slf4j вместо print

2022-09-22 12:54 UTC, Aleksandr-Gurin commented on src/main/java/com/fedag/fedagmusic/repository/PerformerRepository.java
> +    Mono<Long> countOfAllSubscribers();
этот метод должен брать всех пользователей и их подписки, группировать по id исполнителя и вставлять полученные данные в subscribers_count, думаю это легче оформить в отдельной процедуре.

2022-09-29 10:26 UTC, Aleksandr-Gurin requested changes

2022-09-29 10:26 UTC, Aleksandr-Gurin commented on src/main/java/com/fedag/fedagmusic/job/SubscriberCountPerformer.java
> +public class SubscriberCountPerformer {
Давай скедулер удалим, т.к. функционал подсчета подписчиков уже реализован.

2022-09-29 10:26 UTC, Aleksandr-Gurin commented on src/main/java/com/fedag/fedagmusic/repository/PerformerRepository.java
> +    @Query("select sum(subscribers_count) from performer")
этот метод тоже удалим

2022-09-29 10:26 UTC, Aleksandr-Gurin commented on src/main/java/com/fedag/fedagmusic/repository/impl/PlaylistRepoImpl.java
> +public class PlaylistRepoImpl {
Давай переименуем каждый класс Repo по тпиу: PlaylistDatabaseClientImpl. И создадим для каждого класса интерфейс по типу PlaylistDatabaseClient. Весь autowiring делать через интерфейсы

2022-09-29 10:26 UTC, Aleksandr-Gurin commented on src/main/java/com/fedag/fedagmusic/service/impl/PlaylistServiceImpl.java
> +        return playlistRepo.findPlaylistById(id);
добавь эти методы в интерфейс, и удали старые аналоги этих методов, которые теперь не используются

2022-09-29 10:26 UTC, Aleksandr-Gurin commented on src/main/java/com/fedag/fedagmusic/service/impl/SongServiceImpl.java
> +    }
добавь эти методы в интерфейс, и удали старые аналоги этих методов, которые теперь не используются

2022-09-29 10:26 UTC, Aleksandr-Gurin commented on src/main/java/com/fedag/fedagmusic/config/SwaggerConfig.java
> +    public static final String EVERY_DAY_AT_1_AM = "0 0 01 * * *";
Я имел ввиду, yml конфиг. Почитай, как его использовать. Но в любом случае эту строку тоже надо убрать, так как скедулер больше не будет использоваться

2022-09-29 10:26 UTC, Aleksandr-Gurin commented on src/main/java/com/fedag/fedagmusic/controller/PlaylistController.java
> +        return playlistServiceImpl.findPlaylistById(id)
Поменяй поле PlaylistServiceImpl на интерфейс PlaylistService. Всё внедрение(autowiring) необходимо делать через интерфейсы.

2022-09-29 10:26 UTC, Aleksandr-Gurin commented on src/main/java/com/fedag/fedagmusic/controller/SongController.java
> +        return songServiceImpl.findSongById(id)
То же самое с SongServiceImpl

2022-10-03 10:12 UTC, Aleksandr-Gurin approved these changes

2022-10-03 10:12 UTC, Aleksandr-Gurin approved these changes

2022-10-03 10:13 UTC, Aleksandr-Gurin approved these changes
approve

2022-10-03 10:16 UTC, FedorGODUS approved these changes

2022-10-03 10:30 UTC, merged